### ISSUE TITLE
Add option for 12hr time format (instead of 24 hour)?

### ISSUE THREAD

**Issue by spiff72** [squix78/esp8266-weather-station#37]
First of all - this is a VERY slick library.  Well done!

Just curious whether it would be possible in the future to add an option in the code for 12 hour time format (ie 1:03 PM rather than 13:03 ).  I wouldn't even mind if the AM/PM was omitted!

Thanks!

**Comment by pagework** [comment]
Indeed this is very cool. Would like to ditto the 12 hour time format. 
I am numerally dyslexic and it sometimes takes me a bit of time to work out the time.

Thanks for putting this all together for us to enjoy.

**Comment by transfinite8** [comment]
Add to TimeClient.h just after `getHours();`

`String getHours12hr();`

Add to TimeClient.cpp, after function getHours():

```
 String TimeClient::getHours12hr() {
    if (localEpoc == 0) {
      return "--";
    }
    int hours = ((getCurrentEpochWithUtcOffset()  % 86400L) / 3600) % 24;
    
    if (hours == 0) hours = 12;  // Midnight
    if (hours > 12) hours = hours - 12;
    
    if (hours < 10) {
      return "0" + String(hours);
    }
    return String(hours); // print the hour (86400 equals secs per day)

}
```
 Replace calls to getHours() with getHours12hr()

**Comment by neptune2** [comment]
For an alternate implementation of a 12-hour clock format with am/pm indication, see the new [examples/WeatherStationDemoExtendedDST/settings.h](https://github.com/squix78/esp8266-weather-station/blob/master/examples/WeatherStationDemoExtendedDST/settings.h#L137).  Note that this uses the built-in NTP client in the Espressif LWIP core library instead of TimeClient - but could be adapted to work with TimeClient.

When the STYLE_24HR #define is commented out, you get a 12-hour format with am/pm:

```
// Uncomment for 24 Hour style clock
//#define STYLE_24HR
```

See [examples/WeatherStationDemoExtendedDST/WeatherStationDemoExtendedDST.ino](https://github.com/squix78/esp8266-weather-station/blob/master/examples/WeatherStationDemoExtendedDST/WeatherStationDemoExtendedDST.ino#L289) for how this is implemented in the main code.

-Neptune

**Comment by spiff72** [comment]
I hadn't checked back in on this project in a while and just did yesterday. It has a lot of new features!

I am using the extended dst demo now instead of the one I had hacked up and it is working great. 

I am going to close this.

Thanks to Neptune and Daniel for their work on this project!
